export const FETCH_STARSHIP_DETAILS_STARTED = 'FETCH_STARSHIP_DETAILS_STARTED'
export const FETCH_STARSHIP_DETAILS_SUCCESS = 'FETCH_STARSHIP_DETAILS_SUCCESS'
export const FETCH_STARSHIP_DETAILS_REJECTED = 'FETCH_STARSHIP_DETAILS_REJECTED'
export const STARSHIP_DETAILS_DIALOG_CLOSED = 'STARSHIP_DETAILS_DIALOG_CLOSED'

export const FETCH_STARSHIPS_SUCCESS = 'FETCH_STARSHIPS_SUCCESS'
export const FETCH_STARSHIPS_REJECTED = 'FETCH_STARSHIPS_REJECTED'
